#!/bin/bash

file=/var/www/jshawl.com/til/_posts/`date +"%F"`-`date +"%s"`.md
echo "---" >> $file
echo "layout: post" >> $file
echo "---" >> $file
echo "" >> $file
echo "" >> $file
vim -c 'startinsert' $file +5

